[package]
name = "elliptic-curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
finite-fields = { path = "../finite-fields" }
ibig = "0.3.6"
ethers-core = "2.0.8"
revm-primitives = "1.1.2"
